Import('env', 'plugins')

plugins += env.SharedLibrary('independent', ['independent.cpp'])
plugins += env.SharedLibrary('stratified', ['stratified.cpp'])
plugins += env.SharedLibrary('halton', ['halton.cpp'])
plugins += env.SharedLibrary('hammersley', ['hammersley.cpp'])
plugins += env.SharedLibrary('ldsampler', ['ldsampler.cpp'])

Export('plugins')
