Import('env', 'plugins')

plugins += env.SharedLibrary('area', ['area.cpp'])
plugins += env.SharedLibrary('collimated', ['collimated.cpp'])
plugins += env.SharedLibrary('directional', ['directional.cpp'])
plugins += env.SharedLibrary('point', ['point.cpp'])
plugins += env.SharedLibrary('constant', ['constant.cpp'])
plugins += env.SharedLibrary('envmap', ['envmap.cpp'])
plugins += env.SharedLibrary('sky', ['sky.cpp', 'sunsky/skymodel.cpp'])
plugins += env.SharedLibrary('sun', ['sun.cpp'])
plugins += env.SharedLibrary('sunsky', ['sunsky.cpp'])
plugins += env.SharedLibrary('spot', ['spot.cpp'])

Export('plugins')
