Import('env', 'plugins')

plugins += env.SharedLibrary('box', ['box.cpp'])
plugins += env.SharedLibrary('tent', ['tent.cpp'])
plugins += env.SharedLibrary('lanczos', ['lanczos.cpp'])
plugins += env.SharedLibrary('mitchell', ['mitchell.cpp'])
plugins += env.SharedLibrary('catmullrom', ['catmullrom.cpp'])
plugins += env.SharedLibrary('gaussian', ['gaussian.cpp'])

Export('plugins')
