Import('env', 'sys', 'os', 'hasPython')

pythonEnv = env.Clone()
pythonEnv.Append(CPPDEFINES = [['MTS_BUILD_MODULE', 'MTS_MODULE_PYTHON']])
pythonEnv['SHLIBPREFIX']=''
if pythonEnv.has_key('PYTHONINCLUDE'):
	pythonEnv.Prepend(CPPPATH=pythonEnv['PYTHONINCLUDE'])
if pythonEnv.has_key('PYTHONLIBDIR'):
	pythonEnv.Prepend(LIBPATH=pythonEnv['PYTHONLIBDIR'])
if pythonEnv.has_key('PYTHONLIB'):
	pythonEnv.Prepend(LIBS=pythonEnv['PYTHONLIB'])

if hasPython:
	mtspy_plugin = pythonEnv.SharedLibrary('mtspy', ['base.cpp']);
	#mtspy_app = pythonEnv.SharedLibrary('mtspy', ['base.cpp']);

	if sys.platform == "darwin":
		pythonEnv.AddPostAction(mtspy_plugin, 'install_name_tool -id @loader_path/mtspy.dylib $TARGET')
