Import('env', 'plugins')

plugins += env.SharedLibrary('bitmap', ['bitmap.cpp'])
plugins += env.SharedLibrary('scale', ['scale.cpp'])
plugins += env.SharedLibrary('gridtexture', ['gridtexture.cpp'])
plugins += env.SharedLibrary('checkerboard', ['checkerboard.cpp'])
plugins += env.SharedLibrary('vertexcolors', ['vertexcolors.cpp'])
plugins += env.SharedLibrary('wireframe', ['wireframe.cpp'])

Export('plugins')
