Import('env', 'plugins')

plugins += env.SharedLibrary('exrfilm', ['exrfilm.cpp'])
plugins += env.SharedLibrary('pngfilm', ['pngfilm.cpp'])
plugins += env.SharedLibrary('mfilm', ['mfilm.cpp'])

Export('plugins')
