Import('env', 'plugins')

plugins += env.SharedLibrary('#plugins/exrfilm', ['exrfilm.cpp'])
plugins += env.SharedLibrary('#plugins/pngfilm', ['pngfilm.cpp'])
plugins += env.SharedLibrary('#plugins/mfilm', ['mfilm.cpp'])

Export('plugins')
