CXX			  = '~/gcc/bin/x86_64-unknown-linux-gnu-g++'
CXXFLAGS      = ['-O3', '-Wall', '-g', '-pipe', '-march=native', '-msse2', '-ftree-vectorize', '-mfpmath=sse', '-ffast-math', '-fomit-frame-pointer', '-DMTS_DEBUG', '-DSINGLE_PRECISION', '-DMTS_SSE', '-DMTS_HAS_COHERENT_RT']
LINKFLAGS     = []
SHLINKFLAGS   = ['-rdynamic', '-shared', '-fPIC']
BASEINCLUDE   = ['#include', '#dependencies/include']
BASELIB       = ['dl', 'm', 'pthread']
BASELIBDIR    = ['#dependencies/lib']
OEXRINCLUDE   = ['#dependencies/include/OpenEXR']
OEXRLIB       = ['Half', 'IlmImf', 'Iex', 'z']
PNGLIB        = ['png']
JPEGLIB       = ['jpeg']
XERCESINCLUDE = []
XERCESLIB     = ['xerces-c']
GLLIB         = ['GL', 'GLEW', 'Xxf86vm']
