CXX			   = 'g++'
CXXFLAGS       = ['-arch', 'x86_64', '-mmacosx-version-min=10.5', '-march=nocona', '-msse2', '-mfpmath=sse', '-ftree-vectorize', '-ffast-math', '-isysroot', '/Developer/SDKs/MacOSX10.5.sdk', '-O3', '-Wall', '-g', '-pipe', '-DMTS_DEBUG', '-DSINGLE_PRECISION', '-DMTS_SSE', '-DMTS_HAS_COHERENT_RT', '-fopenmp', '-fstrict-aliasing', '-fsched-interblock', '-freorder-blocks']
LINKFLAGS      = ['-framework', 'OpenGL', '-framework', 'Cocoa', '-arch', 'x86_64', '-mmacosx-version-min=10.5', '-Wl,-syslibroot,/Developer/SDKs/MacOSX10.5.sdk']
BASEINCLUDE    = ['#include']
BASELIB        = ['m', 'pthread', 'gomp']
OEXRINCLUDE    = ['#tools/darwin/OpenEXR.framework/Headers/OpenEXR']
OEXRLIBDIR     = ['#tools/darwin/OpenEXR.framework/Resources/lib']
OEXRLIB        = ['Half', 'IlmImf', 'Iex', 'Imath', 'z']
PNGINCLUDE     = ['#tools/darwin/libpng.framework/Headers']
PNGLIBDIR      = ['#tools/darwin/libpng.framework/Resources/lib']
PNGLIB         = ['png']
JPEGINCLUDE    = ['#tools/darwin/libjpeg.framework/Headers']
JPEGLIBDIR     = ['#tools/darwin/libjpeg.framework/Resources/lib']
JPEGLIB        = ['jpeg']
XERCESINCLUDE  = ['#tools/darwin/Xerces-C.framework/Headers']
XERCESLIBDIR   = ['#tools/darwin/Xerces-C.framework/Resources/lib']
XERCESLIB      = ['xerces-c']
GLINCLUDE      = ['#tools/darwin/GLEW.framework/Headers']
GLLIBDIR       = ['#tools/darwin/GLEW.framework/Resources/libs']
GLLIB          = ['GLEW', 'objc']
GLFLAGS        = ['-DGLEW_MX']
BOOSTINCLUDE   = ['#tools/boost']
BOOSTLIB       = ['boost_filesystem-xgcc42-mt-1_39', 'boost_system-xgcc42-mt-1_39']
BOOSTLIBDIR    = ['tools/darwin/libboost.framework/Resources/lib']
COLLADAINCLUDE = ['#tools/windows/include/colladadom', '#tools/windows/include/colladadom/1.4']
COLLADALIB     = ['libCollada14Dom']
COLLADALIBDIR  = ['#tools/darwin/Collada14Dom.framework/Resources/lib']
