Import('env', 'plugins')

plugins += env.SharedLibrary('#plugins/addimages', ['addimages.cpp'])
plugins += env.SharedLibrary('#plugins/joinrgb', ['joinrgb.cpp'])
plugins += env.SharedLibrary('#plugins/cylclip', ['cylclip.cpp'])
plugins += env.SharedLibrary('#plugins/kdbench', ['kdbench.cpp'])
plugins += env.SharedLibrary('#plugins/ttest', ['ttest.cpp'])
plugins += env.SharedLibrary('#plugins/tonemap', ['tonemap.cpp'])
#plugins += env.SharedLibrary('#plugins/uflakefit', ['uflakefit.cpp'])

Export('plugins')
