Import('env', 'sys', 'os', 'hasPython')

pythonEnv = env.Clone()
pythonEnv.Append(CPPDEFINES = [['MTS_BUILD_MODULE', 'MTS_MODULE_PYTHON']])
pythonEnv['SHLIBPREFIX']=''
pythonEnv.RelaxCompilerSettings()

if pythonEnv.has_key('PYTHONINCLUDE'):
	pythonEnv.Prepend(CPPPATH=pythonEnv['PYTHONINCLUDE'])
if pythonEnv.has_key('PYTHONLIBDIR'):
	pythonEnv.Prepend(LIBPATH=pythonEnv['PYTHONLIBDIR'])
if pythonEnv.has_key('PYTHONLIB'):
	pythonEnv.Prepend(LIBS=pythonEnv['PYTHONLIB'])
if pythonEnv.has_key('XERCESINCLUDE'):
	pythonEnv.Prepend(CPPPATH=pythonEnv['XERCESINCLUDE'])
if pythonEnv.has_key('XERCESLIBDIR'):
	pythonEnv.Prepend(LIBPATH=pythonEnv['XERCESLIBDIR'])
if pythonEnv.has_key('XERCESLIB'):
	pythonEnv.Prepend(LIBS=pythonEnv['XERCESLIB'])

if hasPython:
	libpython = pythonEnv.SharedLibrary('mitsuba', 
		['core.cpp', 'render.cpp']);
