Import('env', 'plugins')

plugins += env.SharedLibrary('#plugins/constvolume', ['constvolume.cpp'])
plugins += env.SharedLibrary('#plugins/gridvolume', ['gridvolume.cpp'])
plugins += env.SharedLibrary('#plugins/hgridvolume', ['hgridvolume.cpp'])

Export('plugins')
